Develop (#45)
* test

* test

* refactor(docker): optimize PHP Dockerfile build process

- Consolidate RUN commands into a single layer
- Improve dependency installation structure
- Add better cleanup of temporary files
- Use multi-line format for better readability
- Optimize extension installation with parallel processing

diff --git a/.docker/php/Dockerfile b/.docker/php/Dockerfile
--- a/.docker/php/Dockerfile
+++ b/.docker/php/Dockerfile
@@ -11,30 +11,90 @@ ARG FIXUID_VERSION
 COPY ./.docker/php/cwebp-120-linux-x86-64 /usr/local/bin/cwebp
 COPY ./.docker/php/scripts/* /usr/local/bin/
 
-RUN apk update && apk upgrade \
-    && apk add --update linux-headers \
-    && apk add --virtual build-dependencies libc-dev libxslt-dev freetype-dev libjpeg-turbo-dev libpng-dev libzip-dev libwebp-dev curl \
-    && set -xe \
-    && apk add npm bash bash-completion nano tzdata icu procps git mysql-client \
-    && apk add --virtual .php-deps make \
-    && apk add --virtual .build-deps $PHPIZE_DEPS zlib-dev icu-dev icu-data-full gettext gettext-dev g++ curl-dev \
-    && docker-php-ext-configure hash --with-mhash \
-    && docker-php-ext-configure gd --with-webp --with-jpeg --with-freetype \
-    && docker-php-ext-install gd bcmath intl gettext pdo_mysql opcache soap sockets xsl zip \
-    && pecl channel-update pecl.php.net \
-    && pecl install -o -f redis apcu-$ACPU_VERSION xdebug-$XDEBUG_VERSION \
-    && docker-php-ext-enable redis apcu xdebug \
-    && rm -rf /var/cache/apk/* \
-    && docker-php-source delete \
-    && rm -rf /tmp/pear \
-    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin/ --filename=composer \
-    && curl -SsL https://github.com/boxboat/fixuid/releases/download/v$FIXUID_VERSION/fixuid-$FIXUID_VERSION-linux-amd64.tar.gz | tar -C /usr/local/bin -xzf - \
-    && chmod 4755 /usr/local/bin/fixuid \
-    && mkdir -p /etc/fixuid \
-    && printf "user: $USER_PHP\ngroup: $GROUP_PHP\n" > /etc/fixuid/config.yml \
-    && curl https://files.magerun.net/n98-magerun2.phar --output /usr/local/bin/magerun2 \
-    && mkdir -p /var/run/php/ && chown $USER_PHP:$GROUP_PHP /var/run/php
-
-RUN chmod +x /usr/local/bin/*
+# Install dependencies and PHP extensions in a single layer
+RUN set -eux; \
+    # Update system and install basic tools
+    apk update && apk upgrade; \
+    apk add --no-cache \
+        bash \
+        bash-completion \
+        git \
+        icu \
+        mysql-client \
+        nano \
+        npm \
+        procps \
+        tzdata; \
+    \
+    # Install build dependencies
+    apk add --no-cache --virtual .build-deps \
+        $PHPIZE_DEPS \
+        curl-dev \
+        freetype-dev \
+        g++ \
+        gettext-dev \
+        icu-data-full \
+        icu-dev \
+        libc-dev \
+        libjpeg-turbo-dev \
+        libpng-dev \
+        libwebp-dev \
+        libxslt-dev \
+        libzip-dev \
+        linux-headers \
+        make \
+        zlib-dev; \
+    \
+    # Configure and install PHP extensions
+    docker-php-ext-configure hash --with-mhash; \
+    docker-php-ext-configure gd --with-webp --with-jpeg --with-freetype; \
+    docker-php-ext-install -j$(nproc) \
+        bcmath \
+        gd \
+        gettext \
+        intl \
+        opcache \
+        pdo_mysql \
+        soap \
+        sockets \
+        xsl \
+        zip; \
+    \
+    # Install PECL extensions
+    pecl channel-update pecl.php.net; \
+    pecl install -o -f \
+        redis \
+        apcu-${ACPU_VERSION} \
+        xdebug-${XDEBUG_VERSION}; \
+    docker-php-ext-enable \
+        redis \
+        apcu \
+        xdebug; \
+    \
+    # Install tools
+    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin/ --filename=composer; \
+    curl -SsL https://github.com/boxboat/fixuid/releases/download/v${FIXUID_VERSION}/fixuid-${FIXUID_VERSION}-linux-amd64.tar.gz | tar -C /usr/local/bin -xzf -; \
+    curl -sS https://files.magerun.net/n98-magerun2.phar --output /usr/local/bin/magerun2; \
+    \
+    # Configure permissions and directories
+    chmod 4755 /usr/local/bin/fixuid; \
+    chmod +x /usr/local/bin/*; \
+    mkdir -p /etc/fixuid /var/run/php/; \
+    printf "user: %s\ngroup: %s\n" "$USER_PHP" "$GROUP_PHP" > /etc/fixuid/config.yml; \
+    chown $USER_PHP:$GROUP_PHP /var/run/php; \
+    \
+    # Cleanup
+    docker-php-source delete; \
+    apk del .build-deps; \
+    rm -rf \
+        /tmp/* \
+        /var/cache/apk/* \
+        /var/tmp/* \
+        /usr/share/doc/* \
+        /usr/share/man/* \
+        /usr/share/php/doc/* \
+        /usr/share/php/www.php.net/* \
+        /var/lib/apt/lists/* \
+        /var/cache/apk/*
 
 USER $USER_PHP:$GROUP_PHP
